name: Check widget files

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Get workflow to test against
        run: |
          mkdir tmp
          cd tmp
          wget https://github.com/Biodepot-workflows/salmon-demo/tarball/main -O salmon_demo.tgz
          tar -xzf salmon_demo.tgz
          rm salmon_demo.tgz
          mv $(ls) salmon_demo
          cd salmon_demo/workflow/salmon_demo/widgets/salmon_demo
          
      - name: Get names of widget directories
        run: |
          cd tmp/salmon_demo/workflow/salmon_demo/widgets/salmon_demo
          for dir in */ ; do
            if dir != "icon/" ; do
              echo "$dir"
            done
          done
          
