name: Check widget files

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Get workflow to test against
        run: |
          mkdir tmp
          cd tmp
          wget https://github.com/Biodepot-workflows/salmon-demo/tarball/main -O salmon_demo.tgz
          tar -xzf salmon_demo.tgz
          rm salmon_demo.tgz
          mv $(ls) salmon_demo
          
      - name: Check if important files exist for each widget
        run: |
          cd tmp/salmon_demo/workflow/salmon_demo/widgets/salmon_demo
          for dir in */ ; do
            dir="${dir%/}"
            if [[ "icon" != "$dir" ]] ; then
              if [ ! -f "$dir/Dockerfiles/Dockerfile" ] ; then
                echo "ERROR: $dir/Dockerfiles/Dockerfile does not exist"
                exit 1
              fi
              if [ ! -f "$dir/$dir.attrs" ] ; then
                echo "ERROR: $dir/$dir.attrs does not exist"
                exit 1
              fi
              if [ ! -f "$dir/$dir.json" ] ; then
                echo "ERROR: $dir/$dir.json does not exist"
                exit 1
              fi
              if [ ! -f "$dir/$dir.py" ] ; then
                echo "ERROR: $dir/$dir.py does not exist"
                exit 1
              fi
              if [ ! -f "$dir/$dir.states" ] ; then
                echo "ERROR: $dir/$dir.states does not exist"
                exit 1
              fi
              echo "All necessary files exist for widget $dir"
            fi
          done
          
