name: Check widget files

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Get workflow to test against
        run: |
          mkdir tmp
          cd tmp
          wget https://github.com/Biodepot-workflows/salmon-demo/tarball/main -O salmon_demo.tgz
          tar -xzf salmon_demo.tgz
          rm salmon_demo.tgz
          mv $(ls) salmon_demo
          
      - name: Check if important files exist for each widget
        run: |
          cd tmp/salmon_demo/workflow/salmon_demo/widgets/salmon_demo
          for dir in */ ; do
            dir="${dir%/}"
            if [[ "icon" != "$dir" ]] ; then
              if [ ! -f "$dir/Dockerfiles/Dockerfile" ] ; then
                echo "WARNING: $dir/Dockerfiles/Dockerfile does not exist"
              fi
              if [ ! -f "$dir/icon"/*.png ] && [ ! -f "$dir/icon"/*.jpg ] && [ ! -f "$dir/icon"/*.svg ] ; then
                echo "WARNING: $dir/icon folder does not have an icon file"
              fi
              if [ ! -f "$dir/$dir.attrs" ] ; then
                echo "WARNING: $dir/$dir.attrs does not exist"
              fi
              if [ ! -f "$dir/$dir.json" ] ; then
                echo "WARNING: $dir/$dir.json does not exist"
              fi
              if [ ! -f "$dir/$dir.py" ] ; then
                echo "WARNING: $dir/$dir.py does not exist"
              fi
              if [ ! -f "$dir/$dir.states" ] ; then
                echo "WARNING: $dir/$dir.states does not exist"
              fi
            else
              if [ ! -f icon/*.png ] && [ ! -f icon/*.jpg ] && [ ! -f icon/*.svg ] ; then
                echo "WARNING: No icon found for workflow"
              fi
            fi
          done
          
